package advcash.wsm;

public interface MerchantWebService_PortType extends java.rmi.Remote {
    void validationSendMoneyToAdvcashCard(AuthDTO arg0, AdvcashCardTransferRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, CardIsNotActiveException, LimitPerCardPerDayException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, LifetimeLimitException, CardDoesNotExistException, DatabaseException, LimitPerDayException;

    void validationCurrencyExchange(AuthDTO arg0, CurrencyExchangeRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, CallRestrictionException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException;

    OutcomingTransactionDTO[] history(AuthDTO arg0, advcash.wsm.MerchantAPITransactionFilter arg1) throws java.rmi.RemoteException, AccessDeniedException, LimitsException, CallRestrictionException, NotAuthException, MerchantDisabledException, WrongIpException, WrongParamsException, DatabaseException, InternalException;

    ValidateAccountResultDTO validateAccount(AuthDTO arg0, ValidateAccountRequestDTO arg1) throws java.rmi.RemoteException, AccessDeniedException, LimitsException, CallRestrictionException, NotAuthException, MerchantDisabledException, WrongIpException, UserDoesNotExistException, WrongParamsException, DatabaseException, InternalException;

    AccountPresentDTO[] validateAccounts(AuthDTO arg0, String[] arg1) throws java.rmi.RemoteException, AccessDeniedException, LimitsException, CallRestrictionException, NotAuthException, MerchantDisabledException, WrongIpException, WrongParamsException, DatabaseException, InternalException;

    void validateCurrencyExchange(AuthDTO arg0, TransferRequestDTO arg1, boolean arg2) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, CallRestrictionException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException;

    advcash.wsm.SendMoneyToExmoResultHolder sendMoneyToExmo(AuthDTO arg0, WithdrawToEcurrencyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    void register(AuthDTO arg0, RegistrationRequest arg1) throws java.rmi.RemoteException, RegistrationException, NotAuthException, MerchantDisabledException, WrongIpException, WrongParamsException, DatabaseException, EmailAlreadyExistException, InternalException, BadParametersException;

    void validationSendMoneyToWex(AuthDTO arg0, WithdrawToEcurrencyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    OutcomingTransactionDTO findTransaction(AuthDTO arg0, String arg1) throws java.rmi.RemoteException, AccessDeniedException, LimitsException, CallRestrictionException, NotAuthException, MerchantDisabledException, WrongIpException, WrongParamsException, DatabaseException, InternalException;

    String makeCurrencyExchange(AuthDTO arg0, TransferRequestDTO arg1, boolean arg2) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, CallRestrictionException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException;

    String sendMoneyToEmail(AuthDTO arg0, SendMoneyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, WrongEmailException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, DatabaseException, EmailAlreadyExistException, LimitPerDayException;

    void validationSendMoneyToBankCard(AuthDTO arg0, BankCardTransferRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, advcash.wsm.NotSupportedBankBinException, AccessDeniedException, advcash.wsm.CardNumberIsNotValidException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, advcash.wsm.AdditionalDataRequiredException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, advcash.wsm.NotSupportedCountryException, DatabaseException, LimitPerDayException;

    String sendMoneyToAdvcashCard(AuthDTO arg0, AdvcashCardTransferRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, CardIsNotActiveException, LimitPerCardPerDayException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, LifetimeLimitException, CardDoesNotExistException, DatabaseException, LimitPerDayException;

    String transferBankCard(AuthDTO arg0, BankCardTransferRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, advcash.wsm.CardNumberIsNotValidException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, advcash.wsm.AdditionalDataRequiredException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, LimitPerDayException;

    String currencyExchange(AuthDTO arg0, CurrencyExchangeRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, DatabaseException, LimitPerDayException;

    String sendMoney(AuthDTO arg0, SendMoneyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, advcash.wsm.WalletCurrencyIncorrectException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, DatabaseException, LimitPerDayException;

    void validationSendMoneyToEcurrency(AuthDTO arg0, WithdrawToEcurrencyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    String sendMoneyToEcurrency(AuthDTO arg0, WithdrawToEcurrencyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    String transferAdvcashCard(AuthDTO arg0, advcash.wsm.AdvcashCardTransferRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, UserBlockedException, WrongIpException, UserDoesNotExistException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, BadParametersException, CardIsNotActiveException, InternalException, LimitPerCardPerDayException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, LifetimeLimitException, CardDoesNotExistException, DatabaseException, LimitPerDayException;

    void validateBankCardTransfer(AuthDTO arg0, BankCardTransferRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, advcash.wsm.CardNumberIsNotValidException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, advcash.wsm.AdditionalDataRequiredException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, LimitPerDayException;

    String makeTransfer(AuthDTO arg0, TypeOfTransaction arg1, TransferRequestDTO arg2) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, CallRestrictionException, MerchantDisabledException, WrongIpException, UserBlockedException, advcash.wsm.WalletCurrencyIncorrectException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, CodeIsNotValidException, DatabaseException, ExchangeCurrencyException, LimitPerDayException;

    String emailTransfer(AuthDTO arg0, EmailTransferRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, WrongEmailException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, LimitPerMonthException, advcash.wsm.LimitPerTransactionException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, EmailAlreadyExistException, LimitPerDayException;

    void validationSendMoneyToEmail(AuthDTO arg0, SendMoneyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, WrongEmailException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, DatabaseException, EmailAlreadyExistException, LimitPerDayException;

    String withdrawalThroughExternalPaymentSystem(AuthDTO arg0, advcash.wsm.WithdrawalThroughExternalPaymentSystemRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    String sendMoneyToBankCard(AuthDTO arg0, BankCardTransferRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, advcash.wsm.NotSupportedBankBinException, AccessDeniedException, advcash.wsm.CardNumberIsNotValidException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, advcash.wsm.AdditionalDataRequiredException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, advcash.wsm.NotSupportedCountryException, DatabaseException, LimitPerDayException;

    void validationSendMoneyToExmo(AuthDTO arg0, WithdrawToEcurrencyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    void validateAdvcashCardTransfer(AuthDTO arg0, advcash.wsm.AdvcashCardTransferRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, UserBlockedException, WrongIpException, UserDoesNotExistException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, BadParametersException, CardIsNotActiveException, InternalException, LimitPerCardPerDayException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, LifetimeLimitException, CardDoesNotExistException, DatabaseException, LimitPerDayException;

    void validateWithdrawalThroughExternalPaymentSystem(AuthDTO arg0, advcash.wsm.WithdrawalThroughExternalPaymentSystemRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;

    void validateEmailTransfer(AuthDTO arg0, EmailTransferRequestDTO arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, WrongEmailException, MerchantDisabledException, UserBlockedException, WrongIpException, WrongParamsException, LimitPerMonthException, advcash.wsm.LimitPerTransactionException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, EmailAlreadyExistException, LimitPerDayException;

    void validateTransfer(AuthDTO arg0, TypeOfTransaction arg1, TransferRequestDTO arg2) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, CallRestrictionException, MerchantDisabledException, UserBlockedException, WrongIpException, advcash.wsm.WalletCurrencyIncorrectException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, LimitsException, NotAuthException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException;

    void validationSendMoney(AuthDTO arg0, SendMoneyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, advcash.wsm.WalletCurrencyIncorrectException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, DatabaseException, LimitPerDayException;

    CreateBitcoinInvoiceResult createBitcoinInvoice(AuthDTO arg0, CreateBitcoinInvoiceRequest arg1) throws java.rmi.RemoteException, advcash.wsm.NotAvailableDepositSystemException, AccessDeniedException, MerchantDisabledException, JAXBException, WrongIpException, DuplicateOrderIdException, WrongParamsException, BadParametersException, InternalException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, WalletDoesNotExist, DatabaseException, ApiException;

    CheckCurrencyExchangeResultHolder checkCurrencyExchange(AuthDTO arg0, advcash.wsm.CheckCurrencyExchangeRequest arg1) throws java.rmi.RemoteException, AccessDeniedException, UserBlockedException, DatabaseException, BadParametersException;

    WalletBalanceDTO[] getBalances(AuthDTO arg0) throws java.rmi.RemoteException, AccessDeniedException, LimitsException, CallRestrictionException, NotAuthException, MerchantDisabledException, WrongIpException, WrongParamsException, DatabaseException, InternalException;

    SendMoneyToWexResultHolder sendMoneyToWex(AuthDTO arg0, WithdrawToEcurrencyRequest arg1) throws java.rmi.RemoteException, advcash.wsm.TransactionTemporaryNotAvailableException, advcash.wsm.TransactionIsNotAvailableException, AccessDeniedException, MerchantDisabledException, WrongIpException, UserBlockedException, WrongParamsException, advcash.wsm.LimitPerTransactionException, LimitPerMonthException, InternalException, BadParametersException, advcash.wsm.TransactionFailureException, NotEnoughMoneyException, NotAuthException, NotEnoughMoneyApiException, WalletDoesNotExist, DatabaseException, ExchangeCurrencyException, LimitPerDayException, ApiException;
}
